# Generated by Django 5.0.2 on 2024-05-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
